import { Alert } from 'react-native';
import { createContext, ReactNode, useContext, useEffect, useRef, useState } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { getBooks, getFeatured, getGenres } from '../services/api';
import { getRecommendations } from '../services/recommendations';
import { readStorage, storageKeys, writeStorage } from '../services/storage';
import { RootState } from '../store';
import { hydrateGamification, recordFinished } from '../store/gamificationSlice';
import { addUploadedBook, hydrateLibrary, setCurrentPage, setStatus, toggleFavourite } from '../store/librarySlice';
import { Book, ReadingStatus } from '../types';
import { useUser } from './UserContext';
import { KidsCelebration } from '../components/KidsCelebration';

type ReadingListValue = { books: Book[]; genres: string[]; loading: boolean; refreshing: boolean; error: string | null; offline: boolean; lastSynced: string | null; retry: () => void; refresh: () => Promise<void>; dismissOffline: () => void; clearCachedApiData: () => Promise<void>; selectedGenre: string | null; setSelectedGenre: (genre: string | null) => void; searchText: string; setSearchText: (text: string) => void; recommendations: Book[]; addBook: (book: Book) => void; updateStatus: (id: string, status: ReadingStatus) => void; updatePage: (id: string, page: number) => void; toggleBookFavourite: (id: string) => void };
const ReadingListContext = createContext<ReadingListValue | undefined>(undefined);

export function ReadingListProvider({ children }: { children: ReactNode }) {
  const { user, mode } = useUser(); const [books, setBooks] = useState<Book[]>([]); const [genres, setGenres] = useState<string[]>([]); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState<string | null>(null); const [offline, setOffline] = useState(false); const [lastSynced, setLastSynced] = useState<string | null>(null); const [selectedGenre, setSelectedGenre] = useState<string | null>(null); const [searchText, setSearchTextState] = useState(''); const [showKidsCelebration, setShowKidsCelebration] = useState(false); const dispatch = useDispatch(); const library = useSelector((state: RootState) => state.library); const gamification = useSelector((state: RootState) => state.gamification); const seen = useRef(library.entries);
  const load = async (isRefresh = false) => { isRefresh ? setRefreshing(true) : setLoading(true); setError(null); try { const [loadedBooks, loadedGenres] = await Promise.all([getBooks(), getGenres()]); const syncedAt = new Date().toISOString(); setBooks(loadedBooks); setGenres(loadedGenres); setLastSynced(syncedAt); setOffline(false); await Promise.all([writeStorage(storageKeys.apiBooks, loadedBooks, 'Books cached'), writeStorage(storageKeys.apiGenres, loadedGenres, 'Genres cached'), writeStorage(storageKeys.apiLastSynced, syncedAt, 'API sync saved'), getFeatured().then(featured => writeStorage(storageKeys.apiFeatured, featured, 'Featured books cached')).catch(() => undefined)]); } catch (cause) { const [cachedBooks, cachedGenres, cachedSynced] = await Promise.all([readStorage<Book[]>(storageKeys.apiBooks, []), readStorage<string[]>(storageKeys.apiGenres, []), readStorage<string | null>(storageKeys.apiLastSynced, null)]); if (cachedBooks.length || cachedGenres.length) { setBooks(cachedBooks); setGenres(cachedGenres); setLastSynced(cachedSynced); setOffline(true); } else setError(cause instanceof Error ? cause.message : 'Could not load library.'); } finally { setLoading(false); setRefreshing(false); } };
  useEffect(() => { void load(); }, []);
  useEffect(() => { const hydrate = async () => { const [savedLibrary, savedGame, searches] = await Promise.all([readStorage(storageKeys.queue, library), readStorage(storageKeys.badges, gamification), readStorage<string[]>(storageKeys.searches, [])]); dispatch(hydrateLibrary(savedLibrary)); dispatch(hydrateGamification(savedGame)); if (searches.length) setSearchTextState(searches[0]); }; void hydrate(); }, [dispatch]);
  useEffect(() => { void writeStorage(storageKeys.queue, library, 'Queue saved'); }, [library]);
  useEffect(() => { void writeStorage(storageKeys.badges, gamification, 'Gamification saved'); }, [gamification]);
  useEffect(() => { Object.entries(library.entries).forEach(([id, entry]) => { const previous = seen.current[id]; if (previous && previous.status !== entry.status && entry.status === 'finished') { dispatch(recordFinished(new Date().toISOString().slice(0, 10))); if (mode === 'kids') { setShowKidsCelebration(true); setTimeout(() => setShowKidsCelebration(false), 2400); } else Alert.alert('Great work!', 'Book finished! Your streak and badges have been updated.'); } }); seen.current = library.entries; }, [library.entries, dispatch, mode]);
  const setSearchText = (text: string) => { setSearchTextState(text); if (text.trim()) void writeStorage(storageKeys.searches, [text].slice(0, 5), 'Search saved'); };
  const clearCachedApiData = async () => { const { clearApiCache } = await import('../services/storage'); await clearApiCache(); setLastSynced(null); setOffline(false); Alert.alert('Cached data cleared', 'Fresh book data will be fetched next time you refresh.'); };
  const allBooks = [...books, ...library.uploadedBooks]; const addBook = (book: Book) => { dispatch(addUploadedBook(book)); Alert.alert('Book saved', `${book.title} was added to your library.`); };
  return <ReadingListContext.Provider value={{ books: allBooks, genres, loading, refreshing, error, offline, lastSynced, retry: () => void load(), refresh: () => load(true), dismissOffline: () => setOffline(false), clearCachedApiData, selectedGenre, setSelectedGenre, searchText, setSearchText, recommendations: getRecommendations(user, allBooks, library.entries), addBook, updateStatus: (id, status) => dispatch(setStatus({ id, status })), updatePage: (id, page) => dispatch(setCurrentPage({ id, currentPage: page })), toggleBookFavourite: id => dispatch(toggleFavourite(id)) }}>{children}{mode === 'kids' && <KidsCelebration visible={showKidsCelebration} />}</ReadingListContext.Provider>;
}
export function useReadingList() { const value = useContext(ReadingListContext); if (!value) throw new Error('useReadingList must be used within ReadingListProvider'); return value; }
