// @ts-nocheck
import AsyncStorage from '@react-native-async-storage/async-storage';
import { useEffect, useRef, useState } from 'react';
import { ActivityIndicator, Alert, Animated, FlatList, Image, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useSelector } from 'react-redux';
import { BookCard } from '../components/BookCard';
import { GenreChip } from '../components/GenreChip';
import { ModeToggleCard } from '../components/ModeToggleCard';
import { PrimaryButton } from '../components/PrimaryButton';
import { useReadingList } from '../context/ReadingListContext';
import { useUser } from '../context/UserContext';
import { RootState } from '../store';
import { paletteFor } from '../theme/colors';
import { Book, ReadingMode, ReadingStatus } from '../types';

const genres = ['Fiction', 'Sci-Fi', 'Biography', 'Self-Help'];
function KidsMascot() { const bob = useRef(new Animated.Value(0)).current; useEffect(() => { const animation = Animated.loop(Animated.sequence([Animated.timing(bob, { toValue: 1, duration: 850, useNativeDriver: true }), Animated.timing(bob, { toValue: 0, duration: 850, useNativeDriver: true })])); animation.start(); return () => animation.stop(); }, [bob]); return <Animated.View accessibilityLabel="A friendly reading owl" style={[{ position: 'absolute', right: 22, top: 60, alignItems: 'center', zIndex: 2 }, { transform: [{ translateY: bob.interpolate({ inputRange: [0, 1], outputRange: [0, -12] }) }, { rotate: bob.interpolate({ inputRange: [0, 1], outputRange: ['-4deg', '4deg'] }) }] }]}><Text style={{ fontSize: 65 }}>🦉</Text><Text style={{ fontSize: 26, marginTop: -20 }}>📖</Text></Animated.View>; }
export function KidsHomeScreen({ navigation }: any) { return <View style={{ flex: 1 }}><HomeScreen navigation={navigation} /><KidsMascot /></View>; }
export function KidsBadgesScreen() { const earned = useSelector((state: RootState) => state.gamification.earnedBadges); const badges = [{ id: 'bookworm', icon: '📚', name: 'Bookworm', detail: 'Finish 3 books', color: '#FF7A00' }, { id: 'on-fire', icon: '🔥', name: 'On Fire', detail: 'Reach a 3-day streak', color: '#FF3D81' }, { id: 'explorer', icon: '🗺️', name: 'Explorer', detail: 'Try 4 genres', color: '#17C3B2' }, { id: 'star', icon: '⭐', name: 'Star Reader', detail: 'Read every day', color: '#6C2BD9' }]; return <ScrollView contentContainerStyle={[styles.page, { backgroundColor: '#FFF4B8' }]}><Text style={{ fontSize: 29, fontWeight: '900', color: '#6C2BD9' }}>Badge Treasure Box</Text><Text style={{ fontSize: 16, fontWeight: '700', color: '#5B4774', marginTop: 5 }}>Keep reading to unlock colorful surprises!</Text><View style={{ flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between' }}>{badges.map(badge => { const unlocked = earned.includes(badge.id); return <View key={badge.id} style={[{ width: '47%', minHeight: 190, backgroundColor: '#FFFFFF', borderRadius: 26, borderWidth: 5, padding: 13, alignItems: 'center', justifyContent: 'center', marginTop: 18, shadowColor: badge.color, shadowOpacity: .25, shadowOffset: { width: 0, height: 6 }, shadowRadius: 7, elevation: 6 }, { borderColor: badge.color, opacity: unlocked ? 1 : .55 }]}><View style={{ width: 76, height: 76, borderRadius: 38, alignItems: 'center', justifyContent: 'center', backgroundColor: unlocked ? badge.color : '#D7D1DE' }}><Text style={{ fontSize: 43 }}>{unlocked ? badge.icon : '🔒'}</Text></View><Text style={{ fontSize: 17, fontWeight: '900', color: '#24113D', marginTop: 9, textAlign: 'center' }}>{badge.name}</Text><Text style={{ fontSize: 13, fontWeight: '700', color: '#5B4774', marginTop: 3, textAlign: 'center' }}>{unlocked ? 'Unlocked!' : badge.detail}</Text></View>; })}</View></ScrollView>; }
export function SplashScreen({ navigation }: any) {
  const { restoreSession } = useUser();
  useEffect(() => {
    let active = true;
    const checkAuth = async () => {
      console.log('[Splash] auth check started');
      try {
        // Never leave the user on Splash if native storage is unavailable or slow.
        const stored = await Promise.race([
          Promise.all([AsyncStorage.getItem('auth_token'), AsyncStorage.getItem('auth_mode')]),
          new Promise<[null, null]>(resolve => setTimeout(() => resolve([null, null]), 500)),
        ]);
        const [token, mode] = stored;
        if (!active) return;
        const destination = token && (mode === 'adult' || mode === 'kids') ? (mode === 'adult' ? 'AdultArea' : 'KidsTabs') : 'Login';
        if (mode === 'adult' || mode === 'kids') await restoreSession(mode);
        console.log(`[Splash] auth check completed; navigating to ${destination}`);
        navigation.reset({ index: 0, routes: [{ name: destination }] });
      } catch (error) {
        console.log('[Splash] auth check failed; navigating to Login', error);
        if (active) navigation.reset({ index: 0, routes: [{ name: 'Login' }] });
      }
    };
    const timer = setTimeout(() => { void checkAuth(); }, 1500);
    return () => { active = false; clearTimeout(timer); };
    // The timer must be created once; restoreSession is intentionally read at mount.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [navigation]);
  return <View style={styles.splash}><Text style={styles.splashIcon}>▰</Text><Text style={styles.splashTitle}>ReadingList</Text><Text style={styles.spinner}>◌</Text></View>;
}
export function LoginScreen({ navigation }: any) { const { login } = useUser(); const [email, setEmail] = useState('alex@readinglist.app'); const [password, setPassword] = useState('Reader123'); const [error, setError] = useState(''); const submit = async () => { const result = await login(email, password); if (!result.ok) { setError(result.message); Alert.alert('Login failed', result.message); return; } Alert.alert('Login successful', result.message); navigation.replace('ModeSelect'); }; return <ScrollView contentContainerStyle={styles.auth}><Text style={styles.authIcon}>◉</Text><Text style={styles.title}>Welcome back</Text><Text style={styles.muted}>Sign in to continue your reading journey.</Text><TextInput value={email} onChangeText={setEmail} placeholder="Email address" autoCapitalize="none" style={styles.input} /><TextInput value={password} onChangeText={setPassword} placeholder="Password" secureTextEntry style={styles.input} />{error ? <Text style={styles.loginError}>{error}</Text> : null}<PrimaryButton label="Login" colors={paletteFor('adult')} onPress={submit} /><TouchableOpacity onPress={() => navigation.navigate('Register')}><Text style={styles.link}>Create an account</Text></TouchableOpacity><TouchableOpacity onPress={() => Alert.alert('Coming soon', 'Password reset will be available soon.')}><Text style={styles.link}>Forgot Password?</Text></TouchableOpacity></ScrollView>; }
export function ModeSelectScreen({ navigation }: any) { const { persistMode } = useUser(); const choose = async (mode: ReadingMode) => { await persistMode(mode); Alert.alert('Mode saved', `${mode === 'adult' ? 'Adult' : 'Kids'} mode is ready.`); navigation.replace(mode === 'adult' ? 'AdultArea' : 'KidsTabs'); }; return <View style={styles.mode}><Text style={styles.title}>Who is reading today?</Text><Text style={styles.muted}>Choose a space made for your reader.</Text><View style={styles.modeCards}><ModeToggleCard mode="adult" colors={paletteFor('adult')} onPress={() => choose('adult')} /><ModeToggleCard mode="kids" colors={paletteFor('kids')} onPress={() => choose('kids')} /></View></View>; }
export function HomeScreen({ navigation }: any) { const { mode, user } = useUser(); const { books, genres: liveGenres, selectedGenre, setSelectedGenre, searchText, setSearchText, recommendations, loading, error, retry } = useReadingList(); const colors = paletteFor(mode); const [welcomed, setWelcomed] = useState(false); useEffect(() => { if (!welcomed && user) { setWelcomed(true); Alert.alert(`Welcome${mode === 'kids' ? ', explorer' : ' back'}, ${user.name}!`, 'Your library is ready.'); } }, [welcomed, mode, user]); const filtered = books.filter(book => (!selectedGenre || book.genre === selectedGenre) && `${book.title} ${book.author}`.toLowerCase().includes(searchText.toLowerCase())); if (loading) return <View style={styles.loading}><ActivityIndicator size="large" color={colors.primary} /><Text style={styles.muted}>Loading your library…</Text></View>; if (error) return <View style={styles.loading}><Text style={styles.title}>Could not load books</Text><Text style={styles.muted}>{error}</Text><PrimaryButton label="Retry" colors={colors} onPress={retry} /></View>; const shown = searchText || selectedGenre ? filtered : (mode === 'kids' ? filtered : recommendations); return <ScrollView contentContainerStyle={[styles.page, { backgroundColor: colors.background }]}><View style={styles.homeHeader}>{mode === 'adult' && <TouchableOpacity onPress={() => navigation.openDrawer()}><Ionicons name="menu" size={28} color={colors.text} /></TouchableOpacity>}<Text style={[styles.homeTitle, { color: colors.text }]}>{mode === 'kids' ? `Hi, ${user?.name ?? 'book explorer'}!` : 'Find your next read'}</Text></View><TextInput value={searchText} onChangeText={setSearchText} placeholder="Search books or authors" placeholderTextColor={colors.muted} style={[styles.search, { borderColor: colors.border, color: colors.text }]} /><ScrollView horizontal showsHorizontalScrollIndicator={false} style={styles.genreRow}>{liveGenres.map(genre => <GenreChip key={genre} label={genre} colors={colors} selected={genre === selectedGenre} />)}<TouchableOpacity onPress={() => setSelectedGenre(null)}><Text style={[styles.clear, { color: colors.primary }]}>All</Text></TouchableOpacity></ScrollView><Text style={[styles.sectionTitle, { color: colors.text }]}>{searchText || selectedGenre ? 'Matching books' : mode === 'kids' ? 'Big, brilliant books' : 'Recommended for you'}</Text><ScrollView horizontal showsHorizontalScrollIndicator={false}><View style={styles.cards}>{shown.map(book => <BookCard key={book.id} book={book} colors={colors} kids={mode === 'kids'} onPress={() => navigation.navigate('BookDetails', { bookId: book.id })} />)}</View></ScrollView></ScrollView>; }
export function SearchScreen({ navigation }: any) { const { mode } = useUser(); const { books, searchText, setSearchText } = useReadingList(); const filtered = books.filter(book => `${book.title} ${book.author}`.toLowerCase().includes(searchText.toLowerCase())); return <View style={[styles.page, { backgroundColor: paletteFor(mode).background }]}><Text style={styles.title}>Search library</Text><TextInput value={searchText} onChangeText={setSearchText} placeholder="Title or author" style={styles.input} /><FlatList data={filtered} numColumns={2} keyExtractor={book => book.id} columnWrapperStyle={styles.grid} renderItem={({ item }) => <BookCard book={item} colors={paletteFor(mode)} onPress={() => navigation.navigate('BookDetails', { bookId: item.id })} />} /></View>; }
export function ReadingQueueScreen({ navigation }: any) { const { mode } = useUser(); const { books, updateStatus } = useReadingList(); const entries = useSelector((state: RootState) => state.library.entries); const queued = books.filter(book => entries[book.id]?.status !== 'finished'); const colors = paletteFor(mode); return <ScrollView contentContainerStyle={[styles.page, { backgroundColor: colors.background }]}><Text style={[styles.title, { color: colors.text }]}>My reading queue</Text><Text style={[styles.muted, { marginBottom: 18 }]}>{queued.length} books waiting for you</Text>{queued.map(book => <View key={book.id} style={styles.queueItem}><Image source={{ uri: book.cover }} style={styles.queueCover} /><View style={{ flex: 1 }}><Text style={styles.queueTitle}>{book.title}</Text><Text style={styles.muted}>{book.author} · {entries[book.id]?.status}</Text><TouchableOpacity onPress={() => { updateStatus(book.id, 'reading'); navigation.navigate('BookDetails', { bookId: book.id }); }}><Text style={styles.link}>Start Reading</Text></TouchableOpacity></View></View>)}</ScrollView>; }
export function BookDetailsScreen({ route }: any) { const { mode } = useUser(); const { books, updatePage, updateStatus, toggleBookFavourite } = useReadingList(); const book = books.find(item => item.id === route.params.bookId) as Book; const entry = useSelector((state: RootState) => state.library.entries[book.id]); const favourites = useSelector((state: RootState) => state.library.favourites); const colors = paletteFor(mode); const changePage = (delta: number) => { const page = Math.min(book.pages, Math.max(0, entry.currentPage + delta)); updatePage(book.id, page); if (page === book.pages) updateStatus(book.id, 'finished'); else if (page > 0) updateStatus(book.id, 'reading'); }; return <ScrollView contentContainerStyle={[styles.page, { backgroundColor: colors.background }]}><Image source={{ uri: book.cover }} style={styles.detailCover} /><TouchableOpacity onPress={() => toggleBookFavourite(book.id)}><Text style={styles.link}>{favourites.includes(book.id) ? '♥ Favourite' : '♡ Add favourite'}</Text></TouchableOpacity><Text style={[styles.detailTitle, { color: colors.text }]}>{book.title}</Text><Text style={styles.muted}>{book.author} · {book.genre} · ★ {book.rating}</Text><Text style={[styles.description, { color: colors.text }]}>{book.description}</Text><Text style={styles.queueTitle}>Reading progress: {Math.round((entry.currentPage / book.pages) * 100)}%</Text><View style={styles.controls}><TouchableOpacity onPress={() => changePage(-10)} style={styles.control}><Text style={styles.controlText}>− 10</Text></TouchableOpacity><Text style={styles.pageNumber}>{entry.currentPage} / {book.pages}</Text><TouchableOpacity onPress={() => changePage(10)} style={styles.control}><Text style={styles.controlText}>+ 10</Text></TouchableOpacity></View><PrimaryButton label={entry.status === 'finished' ? 'Finished ✓' : 'Mark as Finished'} colors={colors} onPress={() => { updatePage(book.id, book.pages); updateStatus(book.id, 'finished'); }} /></ScrollView>; }
export function ProfileScreen({ navigation }: any) { const { user, mode, logout } = useUser(); const colors = paletteFor(mode); const streak = useSelector((state: RootState) => state.gamification.streak); const signOut = async () => { await logout(); Alert.alert('Logged out', 'Your saved session has been cleared.'); navigation.navigate('Login'); }; return <View style={[styles.page, { backgroundColor: colors.background }]}><Text style={[styles.title, { color: colors.text }]}>{user?.name}</Text><Text style={styles.muted}>{user?.email}</Text><View style={styles.stat}><Text style={styles.statNumber}>{user?.booksReadThisYear}</Text><Text>books read this year</Text></View><Text style={styles.streak}>🔥 {streak} day streak</Text><PrimaryButton label="Logout" colors={colors} onPress={signOut} /></View>; }
export function BadgesScreen() { const { mode } = useUser(); const earned = useSelector((state: RootState) => state.gamification.earnedBadges); const badges = [{ id: 'bookworm', icon: '📚', name: 'Bookworm', detail: 'Finish 3 books' }, { id: 'on-fire', icon: '🔥', name: 'On Fire', detail: 'Reach a 3-day streak' }, { id: 'explorer', icon: '🗺️', name: 'Explorer', detail: 'Try 4 genres' }, { id: 'star', icon: '⭐', name: 'Star Reader', detail: 'Read every day' }]; return <View style={[styles.page, { backgroundColor: paletteFor(mode).background }]}><Text style={styles.title}>My badges</Text><View style={styles.badgeGrid}>{badges.map(badge => <View key={badge.id} style={[styles.badge, !earned.includes(badge.id) && styles.locked]}><Text style={styles.badgeIcon}>{badge.icon}</Text><Text style={styles.queueTitle}>{badge.name}</Text><Text style={styles.muted}>{badge.detail}</Text></View>)}</View></View>; }
export function StatsScreen() { const { mode } = useUser(); const state = useSelector((s: RootState) => s.gamification); return <View style={[styles.page, { backgroundColor: paletteFor(mode).background }]}><Text style={styles.title}>Reading stats</Text><Text style={styles.statNumber}>{state.totalFinished}</Text><Text style={styles.muted}>books finished in this session</Text><Text style={styles.streak}>🔥 {state.streak} day streak</Text></View>; }
export function PlaceholderScreen({ route }: any) { return <View style={styles.page}><Text style={styles.title}>{route.name}</Text><Text style={styles.muted}>This section is ready for its next iteration.</Text></View>; }
export function LogoutScreen({ navigation }: any) { const { logout } = useUser(); useEffect(() => { const signOut = async () => { await logout(); Alert.alert('Logged out', 'Your saved session has been cleared.'); navigation.getParent()?.getParent()?.reset({ index: 0, routes: [{ name: 'Login' }] }); }; signOut(); }, [logout, navigation]); return <View style={styles.page}><Text style={styles.title}>Signing out…</Text></View>; }
const styles = StyleSheet.create({ splash:{flex:1,justifyContent:'center',alignItems:'center',backgroundColor:'#314B64'}, splashIcon:{fontSize:70,color:'#fff'}, splashTitle:{fontSize:34,fontWeight:'900',color:'#fff'}, spinner:{fontSize:35,color:'#F9D57D',marginTop:35}, auth:{flexGrow:1,justifyContent:'center',padding:28,backgroundColor:'#F6F5F2'}, authIcon:{fontSize:55,textAlign:'center'}, title:{fontSize:28,fontWeight:'900',color:'#1E2935',marginBottom:8}, muted:{color:'#687581',fontSize:14}, input:{backgroundColor:'#fff',borderWidth:1,borderColor:'#E1E4E0',borderRadius:14,padding:15,fontSize:16,marginTop:14}, link:{color:'#314B64',fontWeight:'800',marginTop:16}, loginError:{fontSize:12,color:'#C83232',marginTop:8}, mode:{flex:1,padding:28,justifyContent:'center',backgroundColor:'#F6F5F2'}, modeCards:{marginTop:28}, page:{flexGrow:1,padding:20,paddingBottom:38}, homeHeader:{flexDirection:'row',alignItems:'center',gap:13}, homeTitle:{fontSize:26,fontWeight:'900'}, search:{borderWidth:1,borderRadius:14,padding:13,fontSize:15,marginTop:20,backgroundColor:'#fff'}, genreRow:{marginTop:15}, clear:{fontWeight:'800',padding:10}, sectionTitle:{fontSize:21,fontWeight:'900',marginTop:25,marginBottom:12}, cards:{flexDirection:'row'}, grid:{justifyContent:'space-between',marginBottom:14}, queueItem:{backgroundColor:'#fff',padding:10,borderRadius:15,flexDirection:'row',gap:12,marginBottom:12}, queueCover:{height:104,width:70,borderRadius:9}, queueTitle:{fontWeight:'900',fontSize:16,color:'#1E2935'}, detailCover:{width:170,height:250,borderRadius:16,alignSelf:'center'}, detailTitle:{fontSize:28,fontWeight:'900',marginTop:14}, description:{lineHeight:23,fontSize:15,marginVertical:22}, controls:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',marginVertical:16}, control:{backgroundColor:'#E8EDF0',padding:12,borderRadius:12}, controlText:{fontSize:16,fontWeight:'900'}, pageNumber:{fontWeight:'800'}, stat:{backgroundColor:'#fff',padding:22,borderRadius:16,marginTop:25}, statNumber:{fontSize:38,fontWeight:'900',color:'#314B64'}, streak:{fontSize:20,fontWeight:'900',marginVertical:24}, badgeGrid:{flexDirection:'row',flexWrap:'wrap',justifyContent:'space-between'}, badge:{width:'47%',backgroundColor:'#fff',borderRadius:18,padding:16,alignItems:'center',marginTop:16}, locked:{opacity:.35}, badgeIcon:{fontSize:46,marginBottom:8}, });
