import { useEffect, useState } from 'react';
import { Alert, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { Picker } from '@react-native-picker/picker';
import { useSelector } from 'react-redux';
import { useReadingList } from '../context/ReadingListContext';
import { useUser } from '../context/UserContext';
import { RootState } from '../store';
import { readStorage, storageKeys, writeStorage } from '../services/storage';

type Club = { name: string; memberEmails: string[]; currentBookId: string };
export function ParentDashboardScreen() {
  const { user } = useUser(); const weeklyPagesRead = useSelector((state: RootState) => state.gamification.weeklyPagesRead); const childName = 'Mia'; const childPages = 48; const parentAhead = weeklyPagesRead >= childPages;
  return <ScrollView contentContainerStyle={styles.page}><Text style={styles.title}>Family reading</Text><Text style={styles.subtitle}>This week · a little reading goes a long way</Text><View style={styles.panel}><Text style={styles.panelTitle}>Friendly leaderboard</Text><Row trophy={parentAhead} name={user?.name ?? 'You'} pages={weeklyPagesRead} /><Row trophy={!parentAhead} name={childName} pages={childPages} /><Text style={styles.encouragement}>{parentAhead ? "You're ahead this week — keep enjoying your reading time!" : `${childName} is ahead — a cozy chapter can close the gap!`}</Text></View><View style={styles.panel}><Text style={styles.panelTitle}>{childName}'s progress</Text><Text style={styles.subtitle}>A linked child profile is ready for shared reading encouragement.</Text><Text style={styles.progress}>1 finished · 64% through The Hobbit · 4 day streak</Text></View></ScrollView>;
}
function Row({ trophy, name, pages }: { trophy: boolean; name: string; pages: number }) { return <View style={styles.row}><Text style={styles.trophy}>{trophy ? '🏆' : '📖'}</Text><Text style={styles.rowName}>{name}</Text><Text style={styles.pages}>{pages} pages</Text></View>; }

export function BookClubScreen() {
  const { books } = useReadingList(); const { user } = useUser(); const entries = useSelector((state: RootState) => state.library.entries); const [club, setClub] = useState<Club | null>(null); const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [bookId, setBookId] = useState('');
  useEffect(() => { void readStorage<Club | null>(storageKeys.bookClub, null).then(setClub); }, []);
  const save = (next: Club) => { setClub(next); void writeStorage(storageKeys.bookClub, next, 'Local book club saved'); };
  const create = () => { if (!name.trim() || !bookId) { Alert.alert('Almost there', 'Give your club a name and choose a current book.'); return; } save({ name: name.trim(), currentBookId: bookId, memberEmails: [] }); };
  if (!club) return <ScrollView contentContainerStyle={styles.page}><Text style={styles.title}>Book club</Text><Text style={styles.subtitle}>Create a small shared reading space. It stays on this device for now.</Text><TextInput placeholder="Club name" value={name} onChangeText={setName} style={styles.input} /><View style={styles.picker}><Picker selectedValue={bookId} onValueChange={setBookId}><Picker.Item label="Choose the current book" value="" />{books.filter(book => !book.external).map(book => <Picker.Item key={book.id} label={book.title} value={book.id} />)}</Picker></View><TouchableOpacity style={styles.button} onPress={create}><Text style={styles.buttonText}>Create book club</Text></TouchableOpacity></ScrollView>;
  const currentBook = books.find(book => book.id === club.currentBookId); const own = entries[club.currentBookId]; const percent = currentBook?.pages ? Math.round(((own?.currentPage ?? 0) / currentBook.pages) * 100) : 0; const invite = () => { const normalized = email.trim().toLowerCase(); if (!/^\S+@\S+\.\S+$/.test(normalized)) { Alert.alert('Enter a valid email', 'Invites are saved locally for now.'); return; } if (club.memberEmails.includes(normalized)) return; save({ ...club, memberEmails: [...club.memberEmails, normalized] }); setEmail(''); };
  return <ScrollView contentContainerStyle={styles.page}><Text style={styles.title}>{club.name}</Text><Text style={styles.subtitle}>Current book · {currentBook?.title ?? 'Choose a book'}</Text><View style={styles.panel}><Text style={styles.panelTitle}>Member progress</Text><Row trophy name={user?.name ?? 'You'} pages={own?.currentPage ?? 0} /><Text style={styles.progress}>{percent}% complete</Text>{club.memberEmails.map(member => <View key={member} style={styles.member}><Text style={styles.rowName}>{member}</Text><Text style={styles.subtitle}>Progress will appear when multi-user sync is available.</Text></View>)}</View><Text style={styles.label}>Invite by email</Text><View style={styles.invite}><TextInput value={email} onChangeText={setEmail} placeholder="reader@example.com" autoCapitalize="none" keyboardType="email-address" style={[styles.input, { flex: 1, marginBottom: 0 }]} /><TouchableOpacity style={styles.smallButton} onPress={invite}><Text style={styles.buttonText}>Add</Text></TouchableOpacity></View><Text style={styles.note}>Local-only prototype: invitations and other members’ live progress are stored on this device until backend group support is added.</Text></ScrollView>;
}
const styles = StyleSheet.create({ page: { flexGrow: 1, padding: 24, backgroundColor: '#F6F5F2' }, title: { color: '#1E2935', fontSize: 30, fontWeight: '900' }, subtitle: { color: '#687581', fontSize: 15, lineHeight: 22, marginTop: 6 }, panel: { backgroundColor: '#FFFFFF', borderRadius: 18, padding: 18, marginTop: 20 }, panelTitle: { color: '#314B64', fontSize: 18, fontWeight: '900', marginBottom: 8 }, row: { flexDirection: 'row', alignItems: 'center', paddingVertical: 11, borderBottomWidth: 1, borderColor: '#EDF0F2' }, trophy: { fontSize: 20, marginRight: 10 }, rowName: { flex: 1, color: '#1E2935', fontSize: 16, fontWeight: '800' }, pages: { color: '#314B64', fontWeight: '900' }, encouragement: { color: '#287C4A', fontWeight: '800', lineHeight: 21, marginTop: 14 }, progress: { color: '#314B64', fontWeight: '800', marginTop: 8 }, input: { backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#DDE3E6', borderRadius: 12, padding: 13, fontSize: 15, marginTop: 16 }, picker: { backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#DDE3E6', borderRadius: 12, overflow: 'hidden', marginTop: 12 }, button: { backgroundColor: '#314B64', borderRadius: 13, padding: 15, marginTop: 18, alignItems: 'center' }, smallButton: { backgroundColor: '#314B64', borderRadius: 12, paddingHorizontal: 16, justifyContent: 'center', marginLeft: 8 }, buttonText: { color: '#FFFFFF', fontWeight: '900' }, label: { color: '#1E2935', fontWeight: '800', marginTop: 20 }, invite: { flexDirection: 'row', alignItems: 'center', marginTop: 4 }, member: { paddingTop: 13 }, note: { color: '#687581', fontSize: 12, lineHeight: 18, marginTop: 18 }, });
