import { useState } from 'react';
import { Alert, KeyboardAvoidingView, Platform, ScrollView, StyleSheet, Switch, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { Picker } from '@react-native-picker/picker';
import { PrimaryButton } from '../components/PrimaryButton';
import { paletteFor } from '../theme/colors';
import { useUser } from '../context/UserContext';

type Errors = Record<string, string>;
const emailOk = (value: string) => /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value);
const passwordOk = (value: string) => /[A-Za-z]/.test(value) && /\d/.test(value) && value.length >= 8;
function Field({ label, value, onChangeText, error, ...props }: any) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput value={value} onChangeText={onChangeText} style={[styles.input, error && styles.inputError]} {...props} />{error ? <Text style={styles.error}>{error}</Text> : null}</View>; }
function FormShell({ children }: { children: React.ReactNode }) { return <KeyboardAvoidingView style={styles.flex} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><ScrollView contentContainerStyle={styles.container} keyboardShouldPersistTaps="handled">{children}</ScrollView></KeyboardAvoidingView>; }
export function RegistrationForm({ navigation }: any) {
  const [values, setValues] = useState({ name: '', phone: '', email: '', password: '', confirm: '', gender: '', dob: '', city: '', genre: '', terms: false }); const [errors, setErrors] = useState<Errors>({});
  const { register } = useUser();
  const update = (key: string, value: string | boolean) => setValues(current => ({ ...current, [key]: value }));
  const validate = () => { const next: Errors = {}; if (!/^[A-Za-z ]+$/.test(values.name.trim())) next.name = 'Enter letters and spaces only.'; if (!/^\d{10}$/.test(values.phone)) next.phone = 'Mobile number must be exactly 10 digits.'; if (!emailOk(values.email)) next.email = 'Enter a valid email address.'; if (!passwordOk(values.password)) next.password = 'Use 8+ characters with a letter and number.'; if (values.confirm !== values.password) next.confirm = 'Passwords do not match.'; if (!values.gender) next.gender = 'Choose a gender.'; if (!/^\d{4}-\d{2}-\d{2}$/.test(values.dob)) next.dob = 'Use YYYY-MM-DD.'; if (!values.city) next.city = 'Choose a city.'; if (!values.genre) next.genre = 'Choose a favourite genre.'; if (!values.terms) next.terms = 'You must accept the terms.'; return next; };
  const submit = async () => { const next = validate(); setErrors(next); if (Object.keys(next).length) return; const result = await register({ name: values.name, phone: values.phone, email: values.email, password: values.password, gender: values.gender, dateOfBirth: values.dob, city: values.city, favouriteGenre: values.genre }); if (!result.ok) { setErrors({ email: result.message }); Alert.alert('Registration failed', result.message); return; } Alert.alert('Registration successful', result.message); navigation.goBack(); };
  const ready = Object.keys(validate()).length === 0;
  return <FormShell><Text style={styles.title}>Create your account</Text><Field label="Full name" value={values.name} onChangeText={(v: string) => update('name', v)} error={errors.name} /><Field label="Mobile number" value={values.phone} onChangeText={(v: string) => update('phone', v.replace(/\D/g, ''))} error={errors.phone} keyboardType="number-pad" maxLength={10} /><Field label="Email" value={values.email} onChangeText={(v: string) => update('email', v)} error={errors.email} autoCapitalize="none" keyboardType="email-address" /><Field label="Password" value={values.password} onChangeText={(v: string) => update('password', v)} error={errors.password} secureTextEntry /><Field label="Confirm password" value={values.confirm} onChangeText={(v: string) => update('confirm', v)} error={errors.confirm} secureTextEntry /><Text style={styles.label}>Gender</Text><View style={styles.radioRow}>{['Woman', 'Man', 'Non-binary'].map(option => <TouchableOpacity key={option} onPress={() => update('gender', option)} style={styles.radio}><View style={[styles.radioDot, values.gender === option && styles.radioSelected]} /><Text>{option}</Text></TouchableOpacity>)}</View>{errors.gender ? <Text style={styles.error}>{errors.gender}</Text> : null}<Field label="Date of birth" value={values.dob} onChangeText={(v: string) => update('dob', v)} error={errors.dob} placeholder="YYYY-MM-DD" /><PickerField label="City" value={values.city} onValueChange={(v: string) => update('city', v)} error={errors.city} options={['Colombo', 'Kandy', 'Galle', 'Jaffna']} /><PickerField label="Favourite genre" value={values.genre} onValueChange={(v: string) => update('genre', v)} error={errors.genre} options={['Fiction', 'Sci-Fi', 'Biography', 'Self-Help']} /><View style={styles.switchRow}><Switch value={values.terms} onValueChange={v => update('terms', v)} /><Text style={styles.switchText}>I accept the terms and privacy policy</Text></View>{errors.terms ? <Text style={styles.error}>{errors.terms}</Text> : null}<PrimaryButton label="Register" colors={paletteFor('adult')} onPress={submit} disabled={!ready} /><Text style={ready ? styles.valid : styles.hint}>{ready ? 'All fields are valid.' : 'Complete all required fields to register.'}</Text></FormShell>;
}
function PickerField({ label, value, onValueChange, error, options }: { label: string; value: string; onValueChange: (v: string) => void; error?: string; options: string[] }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><View style={[styles.picker, error && styles.inputError]}><Picker selectedValue={value} onValueChange={onValueChange}><Picker.Item label={`Select ${label.toLowerCase()}`} value="" />{options.map(option => <Picker.Item key={option} label={option} value={option} />)}</Picker></View>{error ? <Text style={styles.error}>{error}</Text> : null}</View>; }
export function ProfileEditForm() { const [values, setValues] = useState({ name: 'Alex Morgan', phone: '0771234567', email: 'alex@readinglist.app', genre: 'Fiction' }); const [errors, setErrors] = useState<Errors>({}); const submit = () => { const next: Errors = {}; if (!/^[A-Za-z ]+$/.test(values.name)) next.name = 'Use alphabetic characters only.'; if (!/^\d{10}$/.test(values.phone)) next.phone = 'Enter exactly 10 digits.'; if (!emailOk(values.email)) next.email = 'Enter a valid email.'; if (!values.genre) next.genre = 'Choose a genre.'; setErrors(next); if (!Object.keys(next).length) Alert.alert('Profile saved', 'Your profile details were updated.'); }; return <FormShell><Text style={styles.title}>Edit profile</Text><Field label="Name" value={values.name} onChangeText={(name: string) => setValues({ ...values, name })} error={errors.name} /><Field label="Phone" value={values.phone} onChangeText={(phone: string) => setValues({ ...values, phone: phone.replace(/\D/g, '') })} error={errors.phone} keyboardType="number-pad" maxLength={10} /><Field label="Email" value={values.email} onChangeText={(email: string) => setValues({ ...values, email })} error={errors.email} autoCapitalize="none" /><PickerField label="Favourite genre" value={values.genre} onValueChange={genre => setValues({ ...values, genre })} error={errors.genre} options={['Fiction', 'Sci-Fi', 'Biography', 'Self-Help']} /><PrimaryButton label="Save profile" colors={paletteFor('adult')} onPress={submit} /></FormShell>; }
export function ReadingPreferencesForm() { const [values, setValues] = useState({ goal: '', format: '', reminder: '', notifications: true }); const [errors, setErrors] = useState<Errors>({}); const submit = () => { const next: Errors = {}; if (!/^\d+$/.test(values.goal) || Number(values.goal) <= 0) next.goal = 'Enter a positive reading goal.'; if (!values.format) next.format = 'Choose a preferred format.'; if (!/^([01]\d|2[0-3]):[0-5]\d$/.test(values.reminder)) next.reminder = 'Use a time such as 19:30.'; setErrors(next); if (!Object.keys(next).length) Alert.alert('Preferences saved', 'Your reading preferences were updated.'); }; return <FormShell><Text style={styles.title}>Reading preferences</Text><Field label="Annual reading goal" value={values.goal} onChangeText={(goal: string) => setValues({ ...values, goal: goal.replace(/\D/g, '') })} error={errors.goal} keyboardType="number-pad" /><PickerField label="Preferred format" value={values.format} onValueChange={format => setValues({ ...values, format })} error={errors.format} options={['Physical', 'Ebook', 'Audiobook']} /><Field label="Daily reminder time" value={values.reminder} onChangeText={(reminder: string) => setValues({ ...values, reminder })} error={errors.reminder} placeholder="19:30" /><View style={styles.switchRow}><Switch value={values.notifications} onValueChange={notifications => setValues({ ...values, notifications })} /><Text style={styles.switchText}>Enable reading reminders</Text></View><PrimaryButton label="Save preferences" colors={paletteFor('adult')} onPress={submit} /></FormShell>; }
const styles = StyleSheet.create({ flex:{flex:1}, container:{padding:22,paddingBottom:42,backgroundColor:'#F6F5F2'}, title:{fontSize:27,fontWeight:'900',color:'#1E2935',marginBottom:18}, field:{marginBottom:13}, label:{fontSize:13,fontWeight:'800',color:'#1E2935',marginBottom:6}, input:{backgroundColor:'#fff',borderWidth:1,borderColor:'#DDE3E6',borderRadius:12,padding:13,fontSize:15}, inputError:{borderColor:'#D94E4E'}, error:{fontSize:12,color:'#C83232',marginTop:4}, picker:{backgroundColor:'#fff',borderWidth:1,borderColor:'#DDE3E6',borderRadius:12,overflow:'hidden'}, radioRow:{flexDirection:'row',flexWrap:'wrap',marginBottom:10,gap:12}, radio:{flexDirection:'row',alignItems:'center',gap:6}, radioDot:{width:19,height:19,borderRadius:10,borderWidth:2,borderColor:'#314B64'}, radioSelected:{backgroundColor:'#314B64',borderWidth:5,borderColor:'#314B64'}, switchRow:{flexDirection:'row',alignItems:'center',marginBottom:18,gap:10}, switchText:{flex:1,fontSize:14,color:'#1E2935'}, hint:{fontSize:12,color:'#687581',textAlign:'center',marginTop:10}, valid:{fontSize:12,color:'#287C4A',textAlign:'center',marginTop:10}, });
