import { useState } from 'react';
import { Alert, Image, KeyboardAvoidingView, Platform, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import * as DocumentPicker from 'expo-document-picker';
import * as ImagePicker from 'expo-image-picker';
import { Picker } from '@react-native-picker/picker';
import { PrimaryButton } from '../components/PrimaryButton';
import { useReadingList } from '../context/ReadingListContext';
import { paletteFor } from '../theme/colors';
import { useUser } from '../context/UserContext';

export function UploadBookForm({ navigation }: any) {
  const { mode } = useUser(); const { genres, addBook } = useReadingList(); const [title, setTitle] = useState(''); const [author, setAuthor] = useState(''); const [genre, setGenre] = useState(''); const [pages, setPages] = useState(''); const [description, setDescription] = useState(''); const [coverUri, setCoverUri] = useState<string | null>(null); const [documentName, setDocumentName] = useState<string | null>(null); const [error, setError] = useState('');
  const pickCover = async () => { const permission = await ImagePicker.requestMediaLibraryPermissionsAsync(); if (!permission.granted) { Alert.alert('Permission needed', 'Allow photo-library access to choose a book cover.'); return; } const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ['images'], allowsEditing: true, aspect: [2, 3], quality: 0.8 }); if (!result.canceled) setCoverUri(result.assets[0].uri); };
  const pickDocument = async () => { const result = await DocumentPicker.getDocumentAsync({ type: ['application/pdf', 'application/epub+zip'], copyToCacheDirectory: true }); if (!result.canceled) setDocumentName(result.assets[0].name); };
  const valid = Boolean(title.trim() && author.trim() && genre && coverUri);
  const save = () => { if (!valid) { setError('Title, author, genre, and a cover image are required.'); return; } addBook({ id: `local-${Date.now()}`, title: title.trim(), author: author.trim(), genre, pages: Number(pages) || 0, description: description.trim() || 'No description added.', rating: 0, cover: coverUri!, queued: true }); navigation.goBack(); };
  return <KeyboardAvoidingView style={styles.flex} behavior={Platform.OS === 'ios' ? 'padding' : undefined}><ScrollView contentContainerStyle={styles.page} keyboardShouldPersistTaps="handled"><Text style={styles.title}>Add a book</Text><Field label="Book title" value={title} onChangeText={setTitle} /><Field label="Author" value={author} onChangeText={setAuthor} /><Text style={styles.label}>Genre</Text><View style={styles.picker}><Picker selectedValue={genre} onValueChange={setGenre}><Picker.Item label="Select a genre" value="" />{genres.map(item => <Picker.Item key={item} label={item} value={item} />)}</Picker></View><Field label="Total pages" value={pages} onChangeText={value => setPages(value.replace(/\D/g, ''))} keyboardType="number-pad" /><Field label="Description" value={description} onChangeText={setDescription} multiline /><TouchableOpacity style={styles.fileButton} onPress={() => void pickCover()}><Text style={styles.fileText}>{coverUri ? 'Change cover image' : 'Pick Cover Image *'}</Text></TouchableOpacity>{coverUri ? <Image source={{ uri: coverUri }} style={styles.cover} /> : null}<TouchableOpacity style={styles.fileButton} onPress={() => void pickDocument()}><Text style={styles.fileText}>{documentName ? `Attached: ${documentName}` : 'Attach PDF/EPUB (optional)'}</Text></TouchableOpacity>{error ? <Text style={styles.error}>{error}</Text> : null}<PrimaryButton label="Save Book" colors={paletteFor(mode)} onPress={save} disabled={!valid} /></ScrollView></KeyboardAvoidingView>;
}
function Field({ label, ...props }: { label: string; value: string; onChangeText: (value: string) => void; [key: string]: any }) { return <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput style={styles.input} {...props} /></View>; }
const styles = StyleSheet.create({ flex:{flex:1}, page:{padding:22,paddingBottom:42,backgroundColor:'#F6F5F2'}, title:{fontSize:28,fontWeight:'900',color:'#1E2935',marginBottom:20}, field:{marginBottom:14}, label:{fontSize:13,fontWeight:'800',color:'#1E2935',marginBottom:6}, input:{backgroundColor:'#fff',borderWidth:1,borderColor:'#DDE3E6',borderRadius:12,padding:13,fontSize:15,minHeight:48}, picker:{backgroundColor:'#fff',borderWidth:1,borderColor:'#DDE3E6',borderRadius:12,overflow:'hidden',marginBottom:14}, fileButton:{padding:15,borderRadius:12,backgroundColor:'#E8EDF0',marginBottom:13}, fileText:{fontWeight:'800',color:'#314B64',textAlign:'center'}, cover:{width:110,height:160,borderRadius:10,alignSelf:'center',marginBottom:14}, error:{color:'#C83232',fontSize:13,marginBottom:12} });
