import { Request, Response } from "express";
import mongoose from "mongoose";
import User from "../models/User"; import Book from "../models/Book"; import Entry from "../models/ReadingListEntry";
const send = (res: Response, status: number, data?: unknown, message?: string) => res.status(status).json({ success: status < 400, ...(data !== undefined && { data }), ...(message && { message }) });
const valid = (id: string) => mongoose.isValidObjectId(id);
export async function getReadingList(req: Request, res: Response) { if (!valid(String(req.params.userId))) return send(res, 400, undefined, "Invalid user id"); if (!await User.exists({ _id: String(req.params.userId) })) return send(res, 404, undefined, "User not found"); const entries = await Entry.find({ userId: String(req.params.userId) }).populate("bookId"); return send(res, 200, entries.map((entry: any) => ({ ...entry.toJSON(), book: entry.bookId }))); }
export async function createReadingListItem(req: Request, res: Response) { const { userId, bookId } = req.body; if (!valid(userId || "") || !valid(bookId || "")) return send(res, 400, undefined, "A valid userId and bookId are required"); if (!await User.exists({ _id: userId }) || !await Book.exists({ _id: bookId })) return send(res, 400, undefined, "A valid userId and bookId are required"); if (await Entry.exists({ userId, bookId })) return send(res, 400, undefined, "Book is already in this reading list"); const status = req.body.status === "want-to-read" ? "to-read" : req.body.status; const currentPage = Number(req.body.currentPage ?? req.body.progress) || 0; const entry = await Entry.create({ userId, bookId, status, currentPage, rating: req.body.rating, notes: req.body.notes, dateFinished: status === "finished" ? new Date() : undefined }); return send(res, 201, entry); }
export async function updateReadingListItem(req: Request, res: Response) { if (!valid(String(req.params.id))) return send(res, 400, undefined, "Invalid reading-list item id"); const old = await Entry.findById(String(req.params.id)); if (!old) return send(res, 404, undefined, "Reading-list item not found"); const updates: Record<string, unknown> = {}; for (const key of ["status", "rating", "notes", "dateFinished"]) if (req.body[key] !== undefined) updates[key] = req.body[key]; if (req.body.progress !== undefined || req.body.currentPage !== undefined) updates.currentPage = Number(req.body.currentPage ?? req.body.progress); if (updates.status === "want-to-read") updates.status = "to-read"; if (updates.status === "finished" && old.status !== "finished") { updates.currentPage = (await Book.findById(old.bookId))?.pages ?? old.currentPage; updates.dateFinished = new Date(); } const entry = await Entry.findByIdAndUpdate(old._id, updates, { new: true, runValidators: true }); return send(res, 200, entry); }
export async function deleteReadingListItem(req: Request, res: Response) { if (!valid(String(req.params.id))) return send(res, 400, undefined, "Invalid reading-list item id"); const entry = await Entry.findByIdAndDelete(String(req.params.id)); return entry ? send(res, 200, undefined, "Reading-list item deleted") : send(res, 404, undefined, "Reading-list item not found"); }
