import { Request, Response } from "express";
import { books, nextId, readingList, reviews, users } from "../data/store";
const send = (res: Response, status: number, data?: unknown, message?: string) => res.status(status).json({ success: status < 400, ...(data !== undefined && { data }), ...(message && { message }) });
const badges = (finished: number, streak: number) => [ ...(finished >= 1 ? ["First Chapter"] : []), ...(finished >= 3 ? ["Bookworm"] : []), ...(streak >= 3 ? ["Consistency Star"] : []), ...(streak >= 7 ? ["Week Warrior"] : []) ];
export const getReviews = (req: Request, res: Response) => { if (!books.some((b) => b.id === req.params.bookId)) return send(res, 404, undefined, "Book not found"); return send(res, 200, reviews.filter((r) => r.bookId === req.params.bookId)); };
export const createReview = (req: Request, res: Response) => { const { bookId, userId, rating, comment } = req.body; if (!bookId || !userId || !comment || !books.some((b) => b.id === bookId) || !users.some((u) => u.id === userId) || Number(rating) < 1 || Number(rating) > 5) return send(res, 400, undefined, "Valid bookId, userId, rating (1-5), and comment are required"); const review = { id: nextId("review", reviews), bookId, userId, rating: Number(rating), comment, createdAt: new Date().toISOString() }; reviews.push(review); return send(res, 201, review); };
export const getGamification = (req: Request, res: Response) => { const user = users.find((u) => u.id === req.params.userId); if (!user) return send(res, 404, undefined, "User not found"); const finished = readingList.filter((r) => r.userId === user.id && r.status === "finished").length; return send(res, 200, { userId: user.id, streakDays: user.streakDays, badges: badges(finished, user.streakDays), finishedBooks: finished }); };
export const checkGamification = (req: Request, res: Response) => { const user = users.find((u) => u.id === req.params.userId); if (!user) return send(res, 404, undefined, "User not found"); const finished = readingList.filter((r) => r.userId === user.id && r.status === "finished").length; user.booksReadThisYear = finished; user.streakDays = finished ? Math.max(1, user.streakDays) : 0; return send(res, 200, { userId: user.id, streakDays: user.streakDays, badges: badges(finished, user.streakDays), finishedBooks: finished }, "Gamification updated"); };
export const parentDashboard = (req: Request, res: Response) => { const parent = users.find((u) => u.id === req.params.userId); if (!parent) return send(res, 404, undefined, "Parent not found"); const children = users.filter((u) => u.parentId === parent.id).map((child) => { const entries = readingList.filter((r) => r.userId === child.id); const finished = entries.filter((r) => r.status === "finished").map((r) => ({ ...r, book: books.find((b) => b.id === r.bookId) })); return { child: { id: child.id, name: child.name, booksReadThisYear: child.booksReadThisYear }, streakDays: child.streakDays, progress: { totalBooks: entries.length, finishedBooks: finished.length, currentlyReading: entries.filter((r) => r.status === "reading").length }, finishedBooks: finished }; }); return send(res, 200, { parentId: parent.id, children }); };
