import { Request, Response } from "express";
import mongoose from "mongoose";
import Book from "../models/Book"; import User from "../models/User"; import Entry from "../models/ReadingListEntry"; import Review from "../models/Review"; import Gamification from "../models/Gamification";
const send = (res: Response, status: number, data?: unknown, message?: string) => res.status(status).json({ success: status < 400, ...(data !== undefined && { data }), ...(message && { message }) });
const badgeList = (finished: number, streak: number) => [...(finished >= 1 ? ["First Chapter"] : []), ...(finished >= 3 ? ["Bookworm"] : []), ...(streak >= 3 ? ["Consistency Star"] : []), ...(streak >= 7 ? ["Week Warrior"] : [])];
export async function getReviews(req: Request, res: Response) { if (!mongoose.isValidObjectId(String(req.params.bookId))) return send(res, 400, undefined, "Invalid book id"); if (!await Book.exists({ _id: String(req.params.bookId) })) return send(res, 404, undefined, "Book not found"); return send(res, 200, await Review.find({ bookId: String(req.params.bookId) })); }
export async function createReview(req: Request, res: Response) { const { bookId, userId, rating } = req.body, text = req.body.text ?? req.body.comment; if (!mongoose.isValidObjectId(bookId || "") || !mongoose.isValidObjectId(userId || "") || !text || Number(rating) < 1 || Number(rating) > 5) return send(res, 400, undefined, "Valid bookId, userId, rating (1-5), and comment are required"); if (!await Book.exists({ _id: bookId }) || !await User.exists({ _id: userId })) return send(res, 400, undefined, "Valid bookId, userId, rating (1-5), and comment are required"); return send(res, 201, await Review.create({ bookId, userId, rating: Number(rating), text, readFormat: req.body.readFormat })); }
async function summary(userId: string) { const user = await User.findById(userId); if (!user) return null; const finished = await Entry.countDocuments({ userId, status: "finished" }); const badges = badgeList(finished, user.streakDays); await Gamification.findOneAndUpdate({ userId }, { userId, streakDays: user.streakDays, badges }, { upsert: true, new: true, setDefaultsOnInsert: true }); return { userId: user.id, streakDays: user.streakDays, badges, finishedBooks: finished }; }
export async function getGamification(req: Request, res: Response) { if (!mongoose.isValidObjectId(String(req.params.userId))) return send(res, 400, undefined, "Invalid user id"); const data = await summary(String(req.params.userId)); return data ? send(res, 200, data) : send(res, 404, undefined, "User not found"); }
export async function checkGamification(req: Request, res: Response) { if (!mongoose.isValidObjectId(String(req.params.userId))) return send(res, 400, undefined, "Invalid user id"); const user = await User.findById(String(req.params.userId)); if (!user) return send(res, 404, undefined, "User not found"); const finished = await Entry.countDocuments({ userId: user._id, status: "finished" }); user.booksReadThisYear = finished; user.streakDays = finished ? Math.max(1, user.streakDays) : 0; await user.save(); const data = await summary(user.id); return send(res, 200, data, "Gamification updated"); }
export async function parentDashboard(req: Request, res: Response) { if (!mongoose.isValidObjectId(String(req.params.userId))) return send(res, 400, undefined, "Invalid user id"); const parent = await User.findById(String(req.params.userId)); if (!parent) return send(res, 404, undefined, "Parent not found"); const children = parent.linkedChildId ? await User.find({ _id: parent.linkedChildId }) : []; const results = await Promise.all(children.map(async child => { const entries = await Entry.find({ userId: child._id }).populate("bookId"); const serialized = entries.map((e: any) => ({ ...e.toJSON(), book: e.bookId })); const finishedBooks = serialized.filter(e => e.status === "finished"); return { child: { id: child.id, name: child.name, booksReadThisYear: child.booksReadThisYear }, streakDays: child.streakDays, progress: { totalBooks: entries.length, finishedBooks: finishedBooks.length, currentlyReading: entries.filter(e => e.status === "reading").length }, finishedBooks }; })); return send(res, 200, { parentId: parent.id, children: results }); }
